### ISSUE TITLE
join method incorrectly handles paths with colons

### ISSUE THREAD

**Issue by benwilber** [gruns/furl#102]
Example:

```
>>> from furl import furl
>>> furl("wss://example.com/").join("foo:1")
furl('http://example.com/foo:1')
```
Notice that it replaced the scheme `wss` with `http`.

Paths without colons work correctly:

```
>>> furl("wss://example.com/").join("foo")
furl('wss://example.com/foo')
```

The same test with `urllib.parse.urljoin` yields the correct result:

```
>>> from urllib.parse import urljoin
>>> urljoin("wss://example.com/", "foo:1")
'wss://example.com/foo:1'
>>> 
```

Python 3.6.6
furl 1.2

**Comment by gruns** [comment]
Fixed in https://github.com/gruns/furl/commit/59e4656f697c0f393ea969fbcdda03c0253ca295, which will ship in the next version of furl, v1.2.1.

```python
>>> furl('wss://example.com/').join('foo:1').url
'wss://example.com/foo:1'
```

Huge thank you for reporting this bug, Ben. Don't hesitate to let me know if
there's anything else I can do for you.
