### ISSUE TITLE
furl fails with unicode username or password in url in python 2.7

### ISSUE THREAD

**Issue by sklnd** [gruns/furl#111]
If you're using http basic auth (which you shouldn't in 2019) with unicode in your username or password (which you shouldn't because nobody implements it the same way) with the username and password in the url (which you shouldn't in 2019), furl will fail to process the url in python 2.7. It works in 3.x. Or at least, it doesn't throw an exception.

Here's a quick test demonstrating the issue.
```
#!/usr/bin/env python2
# -*- coding: utf-8 -*-

from furl import furl

url = u'https://✋:👀@test.com/my/fancy/path'
print(furl(url))
```

In python 3.x, that give me back:
https://%E2%9C%8B:%F0%9F%91%80@test.com/my/fancy/path

In 2.7, I get an exception out of furl, somewhere down in urllib.quote.

**Comment by gruns** [comment]
Fixed in https://github.com/gruns/furl/commit/c1f76a903b90984ba42651774849e57a23a225a1.

```python
>>> from furl import furl
>>> url = u'https://✋:ὄ0@test.com/my/fancy/path'
>>> print(furl(url))
https://%E2%9C%8B:%F0%9F%91%80@test.com/my/fancy/path
```

This fix will ship in the next version of furl, v2.1.0.

Thank you for bringing this issue to my attention, @sklnd. Don't hesitate to let
me know if there's anything I can do for you.
