### ISSUE TITLE
pytest warning

### ISSUE THREAD

**Issue by zeroleo12345** [gruns/furl#116]
/usr/local/lib/python3.7/site-packages/orderedmultidict/orderedmultidict.py:15: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

**Comment by gruns** [comment]
Fixed in furl v2.1.0. Upgrade with

```
$ pip install furl --upgrade
```

Thank you for bringing this issue to my attention, @zeroleo12345. Don't hesitate
to let me know if there's anything else I can do for you.
