### ISSUE TITLE
Different behaviour in py3 and py2

### ISSUE THREAD

**Issue by tjerkw** [gruns/furl#120]
`furl(u'https://www.test.com/?utm_campaign=Test+%2F+Dos+%C3%A0+la+mode+au+mus%C3%A9e+Bourdelle').query.params.get('utm_campaign')` result is different in py2 and py3

In py2 we get:  u'Test / Dos Ã  la mode au musÃ©e Bourdelle'

In py3.7 we get u'Test / Dos à la mode au musée Bourdelle'

This is due to the usage of unquote  in `from six.moves.urllib.parse import unquote`

It might be an issue in that package, or in python 3. I'm not sure

**Comment by gruns** [comment]
Yep. This is a `six` difference between Python3

```python
>>> from six.moves.urllib.parse import unquote
>>> unquote(u'mus%C3%A9e')
'musée'
```

and Python2

```python
>>> from six.moves.urllib.parse import unquote
>>> unquote(u'mus%C3%A9e')
u'mus\xc3\xa9e'
```

Six doesn't make any effort to behave identically under Python2 and Python3. Six exists so the same codebase runs under both Python2 and Python3, but not necessarily with the same behavior, as their standard library's behavior differs.

eg `unquote()` in Python3

```python
>>> from urllib.parse import unquote
>>> unquote(u'mus%C3%A9e')
'musée'
```

and Python2

```python
>>> from urllib import unquote
>>> unquote(u'mus%C3%A9e')
u'mus\xc3\xa9e'
```

Six just provides a unified import name and links to `urllib.parse.unquote` in Python3 and `urllib.unquite` in Python2.

Backing up: do you require identical behavior from furl under both Python 3 and Python 2?

**Comment by tjerkw** [comment]
No we dont require it. But i expected it. Thanks for your explanation and
help.

**Comment by gruns** [comment]
My pleasure!

Closing this Issue. Please re-open this Issue if identical Py2 and Py3 behavior becomes a requirement for you.

Thank you again, Tjerk. Don't hesitate to let me know if there's anything else I can do for you.
