### ISSUE TITLE
Can't call method "is_success" on unblessed reference

### ISSUE THREAD

**Issue by morebrackets** [gruns/furl#123]
```
use strict;
use Furl;
my $furl = Furl::HTTP->new(
    agent   => '',
    timeout => 3,
);
my $res = $furl->get('https://en.wikipedia.org/');
die $res->status_line unless $res->is_success;
print $res->content;
```

ERROR: 
> Can't call method "is_success" on unblessed reference

**Comment by gruns** [comment]
Hi @morebrackets! I believe you meant to file this project under

  * https://github.com/tokuhirom/Furl

a different, Perl project. Name collision.

Please confirm before I close this Issue appropriately.

**Comment by morebrackets** [comment]
My apology. Yes, please delete.
