### ISSUE TITLE
url parsing still accepts semicolon as separator

### ISSUE THREAD

**Issue by atrejut** [gruns/furl#147]
This report is inspired by the latest release, with release note 

> Changed: Drop semicolon query delimiters. See https://bugs.python.org/issue42967.

However, when creating a `furl` from a URL it will still treat semicolons as query delimiter.

```
from furl import furl
uo = furl('https://foo.com/some/path?value=bar;bazz')
uo.args
==> omdict1D([('value', 'bar'), ('bazz', None)])
```

that behaviour seems to be due to https://github.com/gruns/furl/blob/10da29f03949af3a304dd3ca6ca0f358d82d3569/furl/furl.py#L1108

Thanks,

Atreju

**Comment by gruns** [comment]
great find!

fixed https://github.com/gruns/furl/commit/cf6f8181bf5868196b44fcd4a866c7038377be40 and the fix will roll out in v2.1.3, which i'll release shortly

thank you for digging here. super helpful! 🙌

**Comment by atrejut** [comment]
brilliant, thank you for the quick fix!
Not sure how you like to do this, so leaving the issue for you to close?

**Comment by gruns** [comment]
ill close this issue once v2.1.3 ships 🙌

**Comment by cloudyday** [comment]
Kindly asking, what is your release schedule on this?

**Comment by gruns** [comment]
published 🙌 

```
pip install furl --upgrade
```
