### ISSUE TITLE
How handle javascript:void(0)

### ISSUE THREAD

**Issue by colinsarah** [gruns/furl#150]
HI，here url is `https://xxxxx.com/home/javascript:void(0);`
is there any func to get this:`https://xxxxx.com/home`

**Comment by gruns** [comment]
`https://xxxxx.com/home/javascript:void(0);` is a valid URL; none of the path characters of `javascript:void(0);` need to be percent encoded to be a valid path

as such, the to get `https://xxxxx.com/home` from `https://xxxxx.com/home/javascript:void(0);` you can simply pop the last path segment. eg

```python
>>> f = furl('https://xxxxx.com/home/javascript:void(0);')
>>> f.path.segments.pop()
>>> f.url
'https://xxxxx.com/home'
```

does that suffice for your use case?

**Comment by colinsarah** [comment]
thanks！
