### ISSUE TITLE
Maximum recursion depth exceeded error for url with large list

### ISSUE THREAD

**Issue by mwatersinfogix** [gruns/furl#153]
Hello,

I'm attempting to process a url with a value that is a large list of comma separated values e.g.

furl("https://api.example.com/action?ids=0,1,2,3,4,5,6,7,8,9,10,11,12, ... ,998,999,1000")

I am getting a "Maximum recursion depth exceeded" error. My application gives this stack trace output:

RuntimeError('maximum recursion depth exceeded)'
furl.py line="223" function="is_valid_encoded_query_value"
furl.py line="1114" function="_extract_items_from_querystr"
furl.py line="1097" function="_items"
furl.py line="912" function="load"
furl.py line="1413" function="load"
furl.py line="1381" function="__init__"

which indicates it may be a problem with the regex in "is_valid_encoded_query_value".

**Comment by mwatersinfogix** [comment]
We are running on Jython and have discovered this bug https://github.com/jython/jython/issues/121 which is the likely cause of this issue.

**Comment by gruns** [comment]
@mwatersinfogix great digging! 🙌 

this indeed appears to be a jython bug. i can't repro on good 'ol cpython

```python
>>> f = furl('https://api.example.com/action?ids=' + ','.join([str(i) for i in range(1001)]))
(no error)
>>> sys.version
'3.8.2 (default, Jun  8 2021, 11:59:35) \n[Clang 12.0.5 (clang-1205.0.22.11)]'
```

closing this issue. please re-open if you have a workaround for furl that avoids this bug/problem in jython

**Comment by mwatersinfogix** [comment]
@gruns thanks for looking into this.
