### ISSUE TITLE
Adding README to PyPi

### ISSUE THREAD

**Issue by AceofSpades5757** [gruns/furl#154]
Wouldn't adding the README.md to PyPi add value to the project? When going to PyPi it's not as warming to see a short sentence with a link.

**Comment by gruns** [comment]
great suggestion! added in https://github.com/gruns/furl/commit/e29c6947a50a552d68df1c9d85c56b50d48f9298. will ship live to pypi with the next package version 🙌 

thank you, @AceofSpades5757!

**Comment by AceofSpades5757** [comment]
@gruns Thanks, and thank you for your hard work. I really like the package 👍
