### ISSUE TITLE
Is this project being maintained?

### ISSUE THREAD

**Issue by rmonvfer** [gruns/furl#177]
Hello there,

I've been a `furl` user for a while and I really like its interface and ease of use, however, I've noticed that it's been some time since the last commit and I'm wondering if the project might be dead or the author might no longer have the time or energy to maintain it. I've also noticed that all PR's have gone unattended for a couple years as well as most issues.

That being said, I completely understand if the author no longer can maintain the project but it would be pretty sad if it got lost to time due to inactivity. IMHO, I think the community can still keep it up-to-date (by fixing bugs and ensuring compatibility with newer python releases).

I will wait some time but I guess that I'll ultimately just fork the project in an effort to keep it up to date and prevent it from dying. Please let me know if this is ok or if there is any other reason I might not be considering.

**Comment by gruns** [comment]
@rmonvfer ive been (very) busy with startup things. but i do plan to come back and clean up a few things here and there over the holidays

i would *love* to find a maintainer for furl to give it the love it deserves. know anyone potentially interested?

**Comment by gruns** [comment]
i added a note for a maintainer in the readme. in turn, closing this issue 

i would love to find a maintainer for furl to give it the love it deserves. know anyone potentially interested?
