### ISSUE TITLE
missed argument in example in README.md

### ISSUE THREAD

**Issue by bubanoid** [gruns/furl#54]
The example:
>>> from furl import furl
>>> f = furl('http://www.google.com/?one=1&two=2')
>>> f.args['three'] = '3'
>>> del f.args['one']
>>> f.url

I suppose you meant 
>>> f = furl('http://www.google.com/?one=1&two=2&three=3')

**Comment by gruns** [comment]
The example is correct. From the initial URL

```python
f = furl('http://www.google.com/?one=1&two=2')
```

`three` is added with

```python
f.args['three'] = '3'
```

and `one` is removed with

```python
del f.args['one']
```

resulting in `http://www.google.com/?two=2&three=3`.


Thank you for bringing this up, though. Never hurts to double check.

**Comment by bubanoid** [comment]
you are right. 
"Never hurts to double check"...
