### ISSUE TITLE
Adding/modifying query parameters inline

### ISSUE THREAD

**Issue by sbi** [gruns/furl#57]
It seems there's no way to set individual query string parameters inline. Using add() or set() replaces the whole query string. I would love to have an inline version if this:

```
In [5]: url = furl('http://www.a.de/?a=b&x=y')
In [6]: url.args['x'] = 'z'
In [7]: url
Out[7]: furl('http://www.a.de/?a=b&x=z')
```
Am I missing something? If not, I'll try and make a pull request

**Comment by gruns** [comment]
To set individual query string parameters, as in your example above, use the `args` or `query_params` parameter of `add()`.

```python
>>> from furl import furl
>>> f = furl('http://www.a.de/?a=b')
>>> f.add(args={'x':'z'})
>>> f.url
'http://www.a.de/?a=b&x=z'
```

`args` is also the first parameter of `add()`, and thus can be optionally omitted.

```python
>>> f = furl('http://www.a.de/?a=b')
>>> f.add({'x':'z'})
>>> f.url
'http://www.a.de/?a=b&x=z'
```

Does that answer your question?

**Comment by sbi** [comment]
I see I didn't specify the problem well enough, sorry! I'm looking for a way to replace parameters that might or might not be already present in the query string. Here's a better example:

```
>>> furl('http://www.a.de/?page=1').add({'page': '2'}).url
'http://www.a.de/?page=1&page=2
# I actually would like to get 'http://www.a.de/?page=2'
```

I could use set(), but that removes any other unrelated parameters that are in the query string:

```
>>> furl('http://www.a.de/?search=foo&page=1').set({'page': '2'}).url
'http://www.a.de/?page=2
# I actually would like to get 'http://www.a.de/?search=foo&page=2'
```

**Comment by gruns** [comment]
Awesome. You found a bug. `set()` should replace and/or add to query parameters, not remove any.

I'll fix this bug shortly.

Until this bug is fixed, combine `remove()` and `add()`.

```python
>>> from furl import furl
>>> furl('http://www.a.de/?search=foo&page=1').remove(['page']).add({'page': 2}).url
'http://www.a.de/?search=foo&page=2'
```

**Comment by sbi** [comment]
Yes, thank you :-)
