### ISSUE TITLE
Add option to disallow parameter duplication in furl.add()

### ISSUE THREAD

**Issue by poxip** [gruns/furl#60]
That'd be nice if the `.add()` method could have an optional `replace` argument (__False__ by default), because currently the only way to update url's params without param duplication is to call `furl.args.update()`.

**Comment by gruns** [comment]
A `replace` argument doesn't fit `furl.add()` well. When `replace` is True,
`add()` would no longer _add_, it would _replace_. That's counter-intuitive.

Does `furl.args.update()` suffice for your needs? While `furl.args` is
technically an [orderedmultidict](https://github.com/gruns/orderedmultidict), it
retains total method parity with plain old Python dictionaries to be natural to
manipulate, like with `update()`. In other words, treating `furl.args` like a
plain old dictionary and and calling `furl.args.update()` is healthy and normal
use of furl.

Or were you looking for a one-line solution with method chaining? If so, and you
absolutely, positively need to update a URL parameters in one line, you can get
devious

```python
>>> f = furl('http://google.com/?a=1&b=2&c=3')
>>> f.set(f.args.__setitem__('a', 'REPLACE') or f.args).url
'http://google.com/?a=REPLACE&b=2&c=3'
```

But being devious is almost always the wrong solution.

**Comment by poxip** [comment]
The update method works fine for me. Though it'd be nice to see furl having
a update() method with the replace argument (or just a replace method).
Nothing really important, but just wanted to let you know.

**Comment by gruns** [comment]
I'll consider an `update()` (or similar) method for future versions. For now,
closing; `furl.args.update()` suffices. Please re-open this issue if any other
ideas to improve this aspect of furl come to mind.

Thank you again for your time and input Michal.
