### ISSUE TITLE
support args as dict or list

### ISSUE THREAD

**Issue by jzp113** [gruns/furl#61]
Would you plaese add the args like dict or list:
```
furl('http://www.google.com/?one=1').add({'two':[1,2,3,4]})
```

**Comment by gruns** [comment]
To be explicit, your expected behavior is to unpack the list as repeated query
parameters, right? Like

```python
>>> from furl import furl
>>> f = furl('http://www.google.com/?one=1').add({'two':[1,2,3,4]})
>>> f.url
'http://www.google.com/?one=1&two=1&two=2&two=3&two=4'
```

correct?

**Comment by jzp113** [comment]
yes,  `f = furl('http://www.google.com/?one=1').add({'two':{1:1}})` too

**Comment by gruns** [comment]
Which version of furl do you run? It's likely an old version.

The latest furl, v0.4.91, already supports both lists and dictionaries as
parameter values via `add()` and `set()`, as you desire.

```python
>>> import furl
>>> furl.__version__
'0.4.91'
>>> furl.furl('http://www.google.com/?one=1').add({'two':[1,2,3,4]}).url
'http://www.google.com/?one=1&two=1&two=2&two=3&two=4'
>>> furl.furl('http://www.google.com/?one=1').add({'two':{1:1}}).url
'http://www.google.com/?one=1&two=1'
```

You can update to the latest furl with

```
pip install furl --upgrade
```

Does the latest furl, v0.4.91, work for you?

**Comment by gruns** [comment]
@jzp113 Quick follow-up: did upgrading furl to the latest v0.4.92 work for you?

**Comment by jzp113** [comment]
thanks,it's work

**Comment by gruns** [comment]
Great.

Thank you for bringing this issue to my attention, @jzp113.
