### ISSUE TITLE
Port doesn't update on scheme change

### ISSUE THREAD

**Issue by bodgit** [gruns/furl#63]
If I create a scheme-less `furl` object with no explicit port set and then at a later date set the scheme to one which has a known default port, it doesn't update the `port` attribute. For example:

```python
from furl import furl

print(furl('http://example.com').port)
print(furl('unknown://example.com').set(scheme='http').port)
print(furl().set(netloc='example.com').set(scheme='http').port)
```

I get 80, `None`, `None`, whereas I'd expect 80 each time.

**Comment by gruns** [comment]
Wonderful catch.

This bug is fixed in the latest furl v0.4.92. Upgrade with

```
pip install furl --upgrade
```

Thank you for bringing this issue to my attention Matt. Don't hesitate to let me know if there's anything else I can help with.
