### ISSUE TITLE
/ shall be quoted in usernames and passwords

### ISSUE THREAD

**Issue by GaretJax** [gruns/furl#66]
Forward slashes are currently not quoted in username/password when generating the netloc. This causes parsing issues when parsing such a URL. As per https://tools.ietf.org/html/rfc3986 the userinfo part shall not contain `/`.

The`safe=''` argument should be passed to the quote function here: https://github.com/gruns/furl/blob/master/furl/furl.py#L949-L951

**Comment by GaretJax** [comment]
@gruns anything I can do to have the related PR landed and released as soon as possible? :smile: I'll happily help out if I can!

**Comment by gruns** [comment]
Awesome find.

Fixed in ecab80d08d802501e76956fd80b10a08174b3e2a. The fix will be included in the next version of furl.

**Comment by gruns** [comment]
Fix is included in furl v0.4.93. Thank you for your pull request.

Upgrade with

```
pip install --upgrade furl
```

Thank you again for bringing this issue to my attention Jonathan. Don't hesitate  
to let me know if there's anything else I can do for you.

**Comment by GaretJax** [comment]
Awesome, thanks!
