### ISSUE TITLE
Please include license text to PyPI

### ISSUE THREAD

**Issue by ignatenkobrain** [gruns/furl#68]
it will help me in packaging this module in Fedora.

**Comment by ignatenkobrain** [comment]
and API.md please

**Comment by gruns** [comment]
LICENSE.md, README.me, and API.md are all included in furl v0.4.93.

Upgrade with

```
pip install --upgrade furl
```

Thank you for bringing this issue to my attention Igor. Don't hesitate to let me know if there's anything else I can do for you.
