### ISSUE TITLE
Convert unicode URLs to punycode

### ISSUE THREAD

**Issue by jmagnusson** [gruns/furl#73]
I noticed that furl doesn't like to handle unicode URLs. Would it make sense to make furl convert passed in unicode hostnames to punycode? It would make it a lot easier to handle user input. Using the [idna](https://pypi.python.org/pypi/idna) lib makes this trivial, and would be nice to have built in.

Here's how to do it (in Python 3.5):

```python
>>> url = 'http://åäö.se/'
>>> import idna, furl
>>> from urllib.parse import urlparse
>>> parsed = urlparse(url)
>>> parsed = parsed._replace(netloc=idna.encode(parsed.netloc).decode())
>>> punyfied = furl.furl(parsed.geturl())
>>> print(punyfied)
http://xn--4cab6c.se/
```

**Comment by gruns** [comment]
Wonderful suggestion. furl should absolutely support non-ASCII hosts via IDNA
encoding.

I'll add this shortly. Or, pull requests welcome.

That said, IDNA support is a bit delicate.

  1. Python's native idna implementation isn't up to spec: it supports IDNA2003
     but not the latest IDNA2008. See http://bugs.python.org/issue17305.

  2. The idna library (https://pypi.python.org/pypi/idna) supports the latest
     IDNA2008, but furl should require as few dependencies as possible. At best,
     the idna library becomes an optional dependency.

  3. As I've encountered independently, the idna library's `idna.encode()` barfs
     on perfectly valid URLs if the URL resembles an IDNA encoded URL. For
     example, `idna.encode()` barfs on the perfectly valid URL `u'xx--åäö.se'`:

     ```python
     >>> import idna
     >>> idna.encode(u'xx--åäö.se')
     Traceback (most recent call last):
       File "<stdin>", line 1, in <module>
       File "/usr/local/lib/python2.7/dist-packages/idna/core.py", line 355, in encode
         result.append(alabel(label))
       File "/usr/local/lib/python2.7/dist-packages/idna/core.py", line 276, in alabel
         check_label(label)
       File "/usr/local/lib/python2.7/dist-packages/idna/core.py", line 239, in check_label
         check_hyphen_ok(label)
       File "/usr/local/lib/python2.7/dist-packages/idna/core.py", line 134, in check_hyphen_ok
         raise IDNAError('Label has disallowed hyphens in 3rd and 4th position')
     idna.core.IDNAError: Label has disallowed hyphens in 3rd and 4th position
     ```

     If furl uses the idna library, it needs to account for this behavior.

**Comment by jmagnusson** [comment]
Interesting, didn't know about # 3. Perhaps this is something that should be fixed in the `idna` library in itself though?

**Comment by gruns** [comment]
furl v0.5 is hot of the presses and supports IDNA.

```
>>> import furl
>>> furl.__version__
'0.5'
>>> f = furl.furl('http://xn--4cab6c.se/')
>>> f.host
'åäö.se'
>>> f.set(host=u'ドメイン.テスト').url
'http://xn--eckwd4c7c.xn--zckzah/'
```

Update with

```
pip install --upgrade furl
```

I deferred IDNA2008 support. We'll cross that bridge when it becomes an issue.


Thank you for bringing this issue to my attention Jacob. Don't hesitate to let
me know if there's anything else I can do for you.

**Comment by jmagnusson** [comment]
Excellent, seems to be working well for my use cases at least 😀

**Comment by gruns** [comment]
Wunderbar.

Let me know if you encounter any problems or have any comments, suggestions, or recommendations. Feedback is how good products become great.

**Comment by jmagnusson** [comment]
Will do! Thanks for the implementation!
