### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by caulagi** [gruns/furl#76]
Is it possible to add a changelog to the project so that we can see what has changed between releases?  Or am I missing something?

**Comment by gruns** [comment]
A changelog would be great. I'll add such shortly and close this Issue once added.

Until then, you can consult commits before and after tagged releases on the releases page.

  https://github.com/gruns/furl/releases

**Comment by caulagi** [comment]
Yes, I will refer the commits for now. Thanks.

**Comment by gruns** [comment]
Changelog now exists as changelog.txt.

Thank you again for bringing this issue to my attention Pradip. Don't hesitate
to let me know if there's anything else I can do for you.
