### ISSUE TITLE
furl parse some parts of  path as a part of host

### ISSUE THREAD

**Issue by kiwibird01** [gruns/furl#90]
For example:
I define a url using furl this way 
`  self.test_url = furl().set(scheme=scheme, netloc=netloc,
                                                path='/aiccips/OtherPublicity/environmentalProtection.html',
                                                query='requestType=tw'
                                                ).url`
But it got a ValueError:

> ValueError: Invalid host 'gd.gsxt.gov.cn/aiccips'. Host strings must have at least one non-period character, can't contain any of '!@#$%^&'"*()+=:;/', and can't have adjacent periods.

I don't know why `/aiccips` was parsed as a part of host.Was I wrong?

**Comment by gruns** [comment]
What are the values of the `scheme` and `netloc` variables in your code?

```python
self.test_url = furl().set(
    scheme=scheme,
    netloc=netloc,
    path='/aiccips/OtherPublicity/environmentalProtection.html',
    query='requestType=tw').url
```

I'm unable to reproduce the issue you're experiencing without those values.

**Comment by kiwibird01** [comment]
It seems because I passed a wrong ```netloc``` to set()...I'm sorry,just close this issue.

**Comment by gruns** [comment]
No sweat.

Don't hesitate to let me know if there's anything else I can do for you, @kiwibird01.
