### ISSUE TITLE
missing git tags for v1.0.0 and v1.0.1

### ISSUE THREAD

**Issue by wbolster** [gruns/furl#96]
hi,

it seems there are no git tags for 1.0.0 and 1.0.1 though these are published on pypi. not having tags means those versions will not show up on github's releases page.

can you please add those?

**Comment by gruns** [comment]
Added:

  * v1.0.1: https://github.com/gruns/furl/releases/tag/v1.0.1
  * v1.0.0: https://github.com/gruns/furl/releases/tag/v1.0.0

Thank you, as always, Wouter. Don't hesitate to let me know if there's anything
else I can do for you.

**Comment by wbolster** [comment]
thanks for your efforts!
